-- ============================================================
-- المخطط الأساسي (Source of Truth) لأهم عشرة جداول في المنصة:
-- profiles, students, groups, payments, messages, chats, join_requests,
-- sessions, session_ratings, notifications
--
-- ليه الملف ده موجود؟
-- الجداول دي كانت اتعملت يدوياً من لوحة Supabase من أول يوم، ومفيش أي
-- CREATE TABLE ليها في المستودع كله — يعني لو الداتابيز اتمسحت أو حبينا
-- نبني بيئة جديدة (staging/تطوير) من الصفر، كان مستحيل نعرف شكل الجداول
-- إلا من داخل لوحة Supabase نفسها. الملف ده تم بناؤه من فحص فعلي
-- لأعمدة وقيود (constraints) الجداول الحية عبر information_schema.
--
-- ترتيب التشغيل: هذا الملف *قبل* SETUP.sql (اللي بيفترض إن الجداول دي
-- موجودة بالفعل ويضيف عليها أعمدة/سياسات/دوال).
-- آمن لإعادة التشغيل: كل شيء IF NOT EXISTS، فتشغيله على قاعدة بيانات
-- فيها الجداول دي بالفعل لن يكسر أو يكرر شيئاً.
-- ============================================================

-- ---------- الأنواع المخصّصة (ENUM) المستخدمة في الأعمدة ----------
do $$ begin
  if not exists (select 1 from pg_type where typname = 'user_role') then
    create type user_role as enum ('admin','executive','supervisor','teacher','parent','student');
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_type where typname = 'track_type') then
    create type track_type as enum ('both','quran','tarbiya');
  end if;
end $$;

-- ---------- profiles: كل مستخدم مسجّل دخول (كل الأدوار) ----------
-- id نفسه هو مفتاح المصادقة (auth.users.id) — العلاقة بين تسجيل الدخول والبروفايل مباشرة بلا عمود منفصل
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role user_role not null default 'parent',
  full_name text not null,
  initials text,
  phone text,
  created_at timestamptz default now(),
  bio text,
  specialty text,
  rating numeric default 5,
  students_cnt integer default 0,
  years_exp integer default 0,
  gender text,
  available boolean default true,
  avatar_url text,
  email text,
  age integer,
  country text,
  governorate text,
  chosen_track track_type,
  linked_parent_email text,
  onboarded boolean default false,
  residence text,
  is_available boolean default true,
  experience_years integer,
  reports_to uuid references profiles(id),
  title text,
  department text,
  paths text[]
);

-- ---------- groups: الحلقات (عامة وخاصة) ----------
-- ملاحظة معمارية: groups.student_id و students.group_id يشيران لبعضهما (علاقة دائرية) —
-- الحلقة "الخاصة" مرتبطة بطالب واحد عبر student_id، والطالب العادي مرتبط بحلقته عبر group_id.
-- لذلك ننشئ groups بدون قيد student_id أولاً، وبعد إنشاء students نضيف القيد بـ ALTER TABLE.
create table if not exists groups (
  id bigint generated by default as identity primary key,
  name text not null,
  teacher_id uuid references profiles(id),
  track track_type default 'both',
  age_range text,
  meet_time text,
  avg_mastery integer default 0,
  is_private boolean default false,
  student_id bigint,
  quran_path text,
  notes text,
  schedule_days text[],
  schedule_time text,
  schedule_duration_min integer default 30,
  schedule_times jsonb default '{}'::jsonb
);

-- ---------- students: الطلاب ----------
create table if not exists students (
  id bigint generated by default as identity primary key,
  full_name text not null,
  initials text,
  group_id bigint references groups(id),
  parent_id uuid references profiles(id),
  login_id uuid references profiles(id),
  track track_type default 'both',
  age integer,
  pages integer default 0,
  points integer default 0,
  streak integer default 0,
  rank integer default 0,
  attendance integer default 100,
  worship integer default 0,
  mastery integer default 0,
  behavior integer default 0,
  far_review integer default 0,
  phone text,
  created_at timestamptz default now(),
  enrollment_status text default 'pending',
  quran_path text,
  is_subsidized boolean default false,
  chosen_teacher_id uuid references profiles(id),
  sub_start date,
  sub_end date,
  gender text,
  plan_type text,
  package_sessions integer,
  package_fee numeric
);

-- تكملة العلاقة الدائرية بين groups و students
do $$ begin
  if not exists (
    select 1 from information_schema.table_constraints
    where constraint_name = 'groups_student_id_fkey' and table_name = 'groups'
  ) then
    alter table groups add constraint groups_student_id_fkey
      foreign key (student_id) references students(id);
  end if;
end $$;

-- ---------- chats: محادثات الرسائل (طرفين أو أكثر عبر party_ids) ----------
create table if not exists chats (
  id bigint generated by default as identity primary key,
  title text,
  created_at timestamptz default now(),
  party_ids uuid[] default '{}',
  halqa_id bigint references groups(id)
);

-- ---------- messages: رسائل المحادثات ----------
create table if not exists messages (
  id bigint generated by default as identity primary key,
  chat_id bigint references chats(id),
  sender_id uuid references profiles(id),
  body text not null,
  created_at timestamptz default now(),
  sender_name text,
  sender_role text
);

-- ---------- join_requests: طلبات الالتحاق المُقدَّمة وقت التسجيل ----------
create table if not exists join_requests (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id),
  parent_id uuid references profiles(id),
  applicant_id uuid references profiles(id),
  full_name text not null,
  age integer,
  quran_path text,
  prev_experience text,
  difficulties text,
  motivation text,
  request_type text default 'full',
  family_status text,
  father_status text,
  dependents integer,
  affordable numeric,
  status text default 'pending',
  reviewed_by uuid references profiles(id),
  created_at timestamptz default now(),
  plan_type text,
  package_sessions integer,
  package_fee numeric,
  memorization_status text,
  review_status text,
  reading_level text,
  listening_level text
);

-- ---------- payments: دفعات الاشتراك ----------
create table if not exists payments (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id),
  amount numeric not null,
  status text default 'pending',
  paid_at date,
  note text,
  payment_method text,
  reference_number text,
  receipt_url text,
  join_request_id bigint references join_requests(id),
  confirmed_by uuid references profiles(id),
  is_subsidized boolean default false,
  currency_code text default 'EGP'
);

-- ---------- sessions: الحصص المجدولة (عامة وخاصة) ----------
create table if not exists sessions (
  id bigint generated by default as identity primary key,
  group_id bigint references groups(id),
  teacher_id uuid references profiles(id),
  title text not null,
  starts_at timestamptz,
  duration_min integer default 45,
  zoom_url text,
  status text default 'scheduled',
  notes text,
  created_at timestamptz default now(),
  student_id bigint references students(id),
  session_date date,
  session_time text,
  zoom_link text
);

-- ---------- session_ratings: تقييم المعلم لكل حصة ----------
create table if not exists session_ratings (
  id bigint generated by default as identity primary key,
  session_id bigint references sessions(id),
  student_id bigint references students(id),
  teacher_id uuid references profiles(id),
  attendance text,
  memorization text,
  tajweed text,
  review text,
  interaction text,
  behavior text,
  notes text,
  rating_score integer,
  created_at timestamptz default now(),
  unique(session_id)
);

-- ---------- notifications: إشعارات المنصة لكل مستخدم ----------
create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id),
  title text not null,
  body text,
  type text,
  ref_id text,
  is_read boolean default false,
  created_at timestamptz default now(),
  related_type text,
  related_id bigint
);

-- ---------- تفعيل RLS كخطوة أولى (السياسات التفصيلية موجودة في SETUP.sql) ----------
alter table profiles enable row level security;
alter table students enable row level security;
alter table groups enable row level security;
alter table payments enable row level security;
alter table messages enable row level security;
alter table chats enable row level security;
alter table join_requests enable row level security;
alter table sessions enable row level security;
alter table session_ratings enable row level security;
alter table notifications enable row level security;
