-- ============================================================
-- المخطط الأساسي (Source of Truth) لجداول المنصة الستة الأهم:
-- profiles, students, groups, payments, messages, chats
--
-- ليه الملف ده موجود؟
-- الجداول دي كانت اتعملت يدوياً من لوحة Supabase من أول يوم، ومفيش أي
-- CREATE TABLE ليها في المستودع كله — يعني لو الداتابيز اتمسحت أو حبينا
-- نبني بيئة جديدة (staging/تطوير) من الصفر، كان مستحيل نعرف شكل الجداول
-- إلا من داخل لوحة Supabase نفسها. الملف ده تم بناؤه من فحص فعلي
-- لأعمدة وقيود (constraints) الجداول الحية عبر information_schema.
--
-- ترتيب التشغيل: هذا الملف *قبل* SETUP.sql (اللي بيفترض إن الجداول دي
-- موجودة بالفعل ويضيف عليها أعمدة/سياسات/دوال).
-- آمن لإعادة التشغيل: كل شيء IF NOT EXISTS، فتشغيله على قاعدة بيانات
-- فيها الجداول دي بالفعل لن يكسر أو يكرر شيئاً.
-- ============================================================

-- ---------- الأنواع المخصّصة (ENUM) المستخدمة في الأعمدة ----------
do $$ begin
  if not exists (select 1 from pg_type where typname = 'user_role') then
    create type user_role as enum ('admin','executive','supervisor','teacher','parent','student');
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_type where typname = 'track_type') then
    create type track_type as enum ('both','quran','tarbiya');
  end if;
end $$;

-- ---------- profiles: كل مستخدم مسجّل دخول (كل الأدوار) ----------
-- id نفسه هو مفتاح المصادقة (auth.users.id) — العلاقة بين تسجيل الدخول والبروفايل مباشرة بلا عمود منفصل
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role user_role not null default 'parent',
  full_name text not null,
  initials text,
  phone text,
  created_at timestamptz default now(),
  bio text,
  specialty text,
  rating numeric default 5,
  students_cnt integer default 0,
  years_exp integer default 0,
  gender text,
  available boolean default true,
  avatar_url text,
  email text,
  age integer,
  country text,
  governorate text,
  chosen_track track_type,
  linked_parent_email text,
  onboarded boolean default false,
  residence text,
  is_available boolean default true,
  experience_years integer,
  reports_to uuid references profiles(id),
  title text,
  department text,
  paths text[]
);

-- ---------- groups: الحلقات (عامة وخاصة) ----------
-- ملاحظة معمارية: groups.student_id و students.group_id يشيران لبعضهما (علاقة دائرية) —
-- الحلقة "الخاصة" مرتبطة بطالب واحد عبر student_id، والطالب العادي مرتبط بحلقته عبر group_id.
-- لذلك ننشئ groups بدون قيد student_id أولاً، وبعد إنشاء students نضيف القيد بـ ALTER TABLE.
create table if not exists groups (
  id bigint generated by default as identity primary key,
  name text not null,
  teacher_id uuid references profiles(id),
  track track_type default 'both',
  age_range text,
  meet_time text,
  avg_mastery integer default 0,
  is_private boolean default false,
  student_id bigint,
  quran_path text,
  notes text,
  schedule_days text[],
  schedule_time text,
  schedule_duration_min integer default 30,
  schedule_times jsonb default '{}'::jsonb
);

-- ---------- students: الطلاب ----------
create table if not exists students (
  id bigint generated by default as identity primary key,
  full_name text not null,
  initials text,
  group_id bigint references groups(id),
  parent_id uuid references profiles(id),
  login_id uuid references profiles(id),
  track track_type default 'both',
  age integer,
  pages integer default 0,
  points integer default 0,
  streak integer default 0,
  rank integer default 0,
  attendance integer default 100,
  worship integer default 0,
  mastery integer default 0,
  behavior integer default 0,
  far_review integer default 0,
  phone text,
  created_at timestamptz default now(),
  enrollment_status text default 'pending',
  quran_path text,
  is_subsidized boolean default false,
  chosen_teacher_id uuid references profiles(id),
  sub_start date,
  sub_end date,
  gender text,
  plan_type text,
  package_sessions integer,
  package_fee numeric
);

-- تكملة العلاقة الدائرية بين groups و students
do $$ begin
  if not exists (
    select 1 from information_schema.table_constraints
    where constraint_name = 'groups_student_id_fkey' and table_name = 'groups'
  ) then
    alter table groups add constraint groups_student_id_fkey
      foreign key (student_id) references students(id);
  end if;
end $$;

-- ---------- chats: محادثات الرسائل (طرفين أو أكثر عبر party_ids) ----------
create table if not exists chats (
  id bigint generated by default as identity primary key,
  title text,
  created_at timestamptz default now(),
  party_ids uuid[] default '{}',
  halqa_id bigint references groups(id)
);

-- ---------- messages: رسائل المحادثات ----------
create table if not exists messages (
  id bigint generated by default as identity primary key,
  chat_id bigint references chats(id),
  sender_id uuid references profiles(id),
  body text not null,
  created_at timestamptz default now(),
  sender_name text,
  sender_role text
);

-- ---------- payments: دفعات الاشتراك ----------
-- ملاحظة: join_request_id يشير لجدول join_requests، وهو خارج نطاق هذا الملف
-- (لم يُطلب توثيقه ضمن الجداول الستة الأساسية) — نضيف القيد فقط لو الجدول موجود
-- فعلاً، عشان هذا الملف يقدر يشتغل بمفرده حتى قبل ما ننشئ join_requests.
create table if not exists payments (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id),
  amount numeric not null,
  status text default 'pending',
  paid_at date,
  note text,
  payment_method text,
  reference_number text,
  receipt_url text,
  join_request_id bigint,
  confirmed_by uuid references profiles(id),
  is_subsidized boolean default false,
  currency_code text default 'EGP'
);

do $$ begin
  if to_regclass('public.join_requests') is not null
     and not exists (
       select 1 from information_schema.table_constraints
       where constraint_name = 'payments_join_request_id_fkey' and table_name = 'payments'
     ) then
    alter table payments add constraint payments_join_request_id_fkey
      foreign key (join_request_id) references join_requests(id);
  end if;
end $$;

-- ---------- تفعيل RLS كخطوة أولى (السياسات التفصيلية موجودة في SETUP.sql) ----------
alter table profiles enable row level security;
alter table students enable row level security;
alter table groups enable row level security;
alter table payments enable row level security;
alter table messages enable row level security;
alter table chats enable row level security;
