-- ============================================================================
-- 001_document_undocumented_live_tables.sql
--
-- PURPOSE: this file makes no change whatsoever to the live database. Every
-- statement below is `create table if not exists` against tables that ALREADY
-- exist in production (project ref yvloiecymqbhpoizfucl) — verified on
-- 2026-08-08 via read-only introspection (information_schema + pg_policies)
-- through the Supabase Management API. It exists purely so this ~26-table
-- part of the schema — most of it the entire Quran memorization curriculum
-- engine (quran_*) plus operational tables (attendance, notes, husoon_marks,
-- link_invites, teacher_slots, etc.) — has a source of truth in version
-- control. Before this file, none of these tables were defined anywhere in
-- the repo (see README.md's own admission and the audit report).
--
-- Safe to run on the live project any time: every CREATE is guarded with
-- `if not exists`, so re-running it against a database that already has
-- these tables is a no-op. It is only load-bearing for disaster recovery /
-- spinning up a fresh environment from scratch.
--
-- RLS finding worth noting: every one of these tables already has RLS
-- ENABLED with real, non-trivial policies live in production (confirmed via
-- pg_policies) — including `quran_plan_fortress_rates`, which the migration
-- `2026_plan_custom_rates_and_starting_station.sql` in this repo only left a
-- TODO comment for. The policy exists live; the repo was just out of date.
-- This file also documents the policies actually in force today.
--
-- Depends on: helper functions already defined in SETUP.sql —
-- is_admin(), my_role(), can_see_student(student_id uuid|bigint).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Operational / legacy tables
-- ---------------------------------------------------------------------------

create table if not exists app_settings (
  key text primary key,
  value text,
  updated_by uuid references profiles(id),
  updated_at timestamptz default now()
);
alter table app_settings enable row level security;
drop policy if exists "settings read" on app_settings;
create policy "settings read" on app_settings for select using (true);
drop policy if exists "settings write" on app_settings;
create policy "settings write" on app_settings for all
  using (is_admin() or my_role() in ('supervisor','executive'))
  with check (is_admin() or my_role() in ('supervisor','executive'));

create table if not exists programs (
  id bigint generated by default as identity primary key,
  name text not null,
  duration text,
  sessions integer,
  fee numeric default 0,
  quran_system_id uuid references quran_systems(id)
);
alter table programs enable row level security;
drop policy if exists "programs read" on programs;
create policy "programs read" on programs for select using (true);
drop policy if exists "programs admin" on programs;
create policy "programs admin" on programs for all using (is_admin()) with check (is_admin());

create table if not exists attendance (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id),
  day date default current_date,
  status text default 'present',
  date date default current_date,
  unique (student_id, day)
);
alter table attendance enable row level security;
drop policy if exists "att see" on attendance;
create policy "att see" on attendance for select using (can_see_student(student_id));
drop policy if exists "att write" on attendance;
create policy "att write" on attendance for all using (can_see_student(student_id)) with check (can_see_student(student_id));

create table if not exists notes (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id),
  author_id uuid references profiles(id),
  author_name text,
  body text not null,
  created_at timestamptz default now()
);
alter table notes enable row level security;
drop policy if exists "notes see" on notes;
create policy "notes see" on notes for select using (can_see_student(student_id));
drop policy if exists "notes write" on notes;
create policy "notes write" on notes for all using (can_see_student(student_id)) with check (can_see_student(student_id));

create table if not exists content (
  id bigint generated by default as identity primary key,
  title text not null,
  type text,
  track track_type default 'both',
  level text,
  url text,
  created_at timestamptz default now(),
  group_id bigint references groups(id),
  author_id uuid references profiles(id),
  quran_path text
);
alter table content enable row level security;
drop policy if exists "content read" on content;
create policy "content read" on content for select using (true);
drop policy if exists "content admin" on content;
create policy "content admin" on content for all using (is_admin()) with check (is_admin());

create table if not exists teacher_slots (
  id bigint generated by default as identity primary key,
  teacher_id uuid references profiles(id),
  weekday integer not null,
  time_label text not null,
  taken boolean default false
);
alter table teacher_slots enable row level security;
drop policy if exists "slots read" on teacher_slots;
create policy "slots read" on teacher_slots for select using (true);
drop policy if exists "slots write" on teacher_slots;
create policy "slots write" on teacher_slots for all using (teacher_id = auth.uid() or is_admin()) with check (teacher_id = auth.uid() or is_admin());

create table if not exists placement_tests (
  id bigint generated by default as identity primary key,
  student_name text,
  parent_id uuid references profiles(id),
  answers jsonb,
  score integer,
  level text,
  recommended text,
  created_at timestamptz default now()
);
alter table placement_tests enable row level security;
drop policy if exists "place see" on placement_tests;
create policy "place see" on placement_tests for select
  using (is_admin() or my_role() in ('supervisor','executive','teacher') or parent_id = auth.uid());
drop policy if exists "place new" on placement_tests;
create policy "place new" on placement_tests for insert
  with check (is_admin() or my_role() in ('supervisor','executive','teacher') or parent_id = auth.uid());

create table if not exists enroll_requests (
  id bigint generated by default as identity primary key,
  parent_id uuid references profiles(id),
  student_name text,
  age integer,
  track track_type default 'both',
  teacher_id uuid references profiles(id),
  preferred_time text,
  status text default 'new',
  created_at timestamptz default now()
);
alter table enroll_requests enable row level security;
drop policy if exists "req mine" on enroll_requests;
create policy "req mine" on enroll_requests for select using (parent_id = auth.uid() or is_admin());
drop policy if exists "req new" on enroll_requests;
create policy "req new" on enroll_requests for insert with check (parent_id = auth.uid() or parent_id is null);
drop policy if exists "req admin" on enroll_requests;
create policy "req admin" on enroll_requests for update using (is_admin());

-- security-sensitive: backs the account-linking RPCs (create_linked_account, accept_link_invite)
create table if not exists link_invites (
  id bigint generated by default as identity primary key,
  inviter_id uuid references profiles(id),
  inviter_role text,
  invite_name text,
  invite_email text not null,
  invite_phone text,
  student_id bigint references students(id),
  status text default 'pending',
  created_at timestamptz default now(),
  invite_password text
);
alter table link_invites enable row level security;
drop policy if exists "li_see" on link_invites;
create policy "li_see" on link_invites for select
  using (is_admin() or inviter_id = auth.uid() or invite_email = (select email from profiles where id = auth.uid()));
drop policy if exists "li_write" on link_invites;
create policy "li_write" on link_invites for all
  using (is_admin() or inviter_id = auth.uid() or invite_email = (select email from profiles where id = auth.uid()))
  with check (is_admin() or inviter_id = auth.uid() or invite_email = (select email from profiles where id = auth.uid()));

create table if not exists homework (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  group_id bigint references groups(id),
  teacher_id uuid references profiles(id),
  due_date date,
  created_at timestamptz default now()
);
alter table homework enable row level security;
drop policy if exists "hw see" on homework;
create policy "hw see" on homework for select
  using (is_admin() or teacher_id = auth.uid() or exists (select 1 from students s where s.group_id = homework.group_id and can_see_student(s.id)));
drop policy if exists "hw write" on homework;
create policy "hw write" on homework for all using (is_admin() or teacher_id = auth.uid()) with check (is_admin() or teacher_id = auth.uid());

create table if not exists homework_submissions (
  id bigint generated by default as identity primary key,
  homework_id bigint references homework(id),
  student_id bigint references students(id),
  status text default 'pending',
  submitted_at timestamptz,
  unique (homework_id, student_id)
);
alter table homework_submissions enable row level security;
drop policy if exists "hws see" on homework_submissions;
create policy "hws see" on homework_submissions for select
  using (is_admin() or can_see_student(student_id) or exists (select 1 from homework h where h.id = homework_submissions.homework_id and h.teacher_id = auth.uid()));
drop policy if exists "hws write" on homework_submissions;
create policy "hws write" on homework_submissions for all using (can_see_student(student_id) or is_admin()) with check (can_see_student(student_id) or is_admin());

create table if not exists assignments (
  id bigint generated by default as identity primary key,
  group_id bigint references groups(id),
  student_id bigint references students(id),
  teacher_id uuid references profiles(id),
  session_id bigint references sessions(id),
  title text not null,
  kind text default 'link',
  url text,
  notes text,
  due_date date,
  status text default 'pending',
  done_at timestamptz,
  created_at timestamptz default now()
);
alter table assignments enable row level security;
drop policy if exists "asg see" on assignments;
create policy "asg see" on assignments for select
  using (is_admin() or my_role() in ('supervisor','executive') or teacher_id = auth.uid() or can_see_student(student_id));
drop policy if exists "asg write" on assignments;
create policy "asg write" on assignments for all
  using (is_admin() or my_role() in ('supervisor','executive') or teacher_id = auth.uid())
  with check (is_admin() or my_role() in ('supervisor','executive') or teacher_id = auth.uid());
drop policy if exists "asg student status" on assignments;
create policy "asg student status" on assignments for update using (can_see_student(student_id)) with check (can_see_student(student_id));

-- ---------------------------------------------------------------------------
-- Daily self-tracking tables (dashboard / character-building widgets)
-- ---------------------------------------------------------------------------

create table if not exists husoon_marks (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id),
  day date default current_date,
  hisn_no integer not null,
  hisn_name text,
  detail text,
  state mark_state default 'todo',
  unique (student_id, day, hisn_no)
);
alter table husoon_marks enable row level security;
drop policy if exists "husoon see" on husoon_marks;
create policy "husoon see" on husoon_marks for select using (can_see_student(student_id));
drop policy if exists "husoon write" on husoon_marks;
create policy "husoon write" on husoon_marks for all using (can_see_student(student_id)) with check (can_see_student(student_id));
-- NOTE: this is the legacy, template-driven daily-completion table described in
-- the audit report as "System B" — disconnected from the real curriculum engine
-- (quran_plan_wards/quran_ward_progress below). Do not delete; see the
-- migration plan in 002_husoon_marks_migration_plan.sql before any consolidation.

create table if not exists worship_marks (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id),
  week_start date default current_date,
  worship text not null,
  day_idx integer not null,
  state mark_state default 'none',
  unique (student_id, week_start, worship, day_idx)
);
alter table worship_marks enable row level security;
drop policy if exists "worship see" on worship_marks;
create policy "worship see" on worship_marks for select using (can_see_student(student_id));
drop policy if exists "worship write" on worship_marks;
create policy "worship write" on worship_marks for all using (can_see_student(student_id)) with check (can_see_student(student_id));

create table if not exists challenge_tasks (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id),
  day date default current_date,
  task text not null,
  points integer default 5,
  done boolean default false
);
alter table challenge_tasks enable row level security;
drop policy if exists "chal see" on challenge_tasks;
create policy "chal see" on challenge_tasks for select using (can_see_student(student_id));
drop policy if exists "chal write" on challenge_tasks;
create policy "chal write" on challenge_tasks for all using (can_see_student(student_id)) with check (can_see_student(student_id));

create table if not exists daily_hifz (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id),
  date date not null default current_date,
  new_hifz_done boolean default false,
  new_hifz_pages numeric default 0,
  new_hifz_note text,
  review_near_done boolean default false,
  review_near_note text,
  daily_read_done boolean default false,
  daily_read_pages numeric default 0,
  review_far_done boolean default false,
  review_far_note text,
  listening_done boolean default false,
  listening_note text,
  general_note text,
  created_at timestamptz default now(),
  unique (student_id, date)
);
alter table daily_hifz enable row level security;
drop policy if exists "dh see" on daily_hifz;
create policy "dh see" on daily_hifz for select using (can_see_student(student_id));
drop policy if exists "dh write" on daily_hifz;
create policy "dh write" on daily_hifz for all using (can_see_student(student_id)) with check (can_see_student(student_id));
-- NOTE: appears to be an even earlier prototype of the daily-tracking concept,
-- unused by any PAGES.* function found in index.html as of this audit. Kept
-- documented but flagged as a candidate for removal once confirmed unused.

-- ---------------------------------------------------------------------------
-- Quran curriculum engine (quran_*) — the real "حصون" system
-- ---------------------------------------------------------------------------

create table if not exists quran_systems (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  track text not null default 'fortresses',
  target_audience text,
  default_start_date date,
  expected_duration_weeks integer,
  study_days integer[] default '{1,2,3,4,5}',
  rest_days integer[] default '{6,7}',
  status text default 'draft',
  created_by uuid references profiles(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  plan_type text not null default 'rasokh',
  path_key text
);
alter table quran_systems enable row level security;
drop policy if exists "staff read quran_systems" on quran_systems;
create policy "staff read quran_systems" on quran_systems for select to authenticated using (true);
drop policy if exists "qsys_admin_all" on quran_systems;
create policy "qsys_admin_all" on quran_systems for all
  using (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')))
  with check (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')));

create table if not exists quran_stations (
  id uuid primary key default gen_random_uuid(),
  system_id uuid references quran_systems(id),
  order_index integer not null,
  name text not null,
  description text,
  entry_conditions text,
  exit_conditions text,
  expected_duration_days integer,
  min_completion_pct numeric default 80,
  min_mastery_pct numeric default 70,
  requires_exam boolean default false,
  created_at timestamptz default now(),
  station_kind text default 'hifz',
  boundary_surah_from integer,
  boundary_surah_to integer,
  boundary_ayah_from integer,
  boundary_ayah_to integer,
  force_forward boolean default false
);
alter table quran_stations enable row level security;
drop policy if exists "staff read quran_stations" on quran_stations;
create policy "staff read quran_stations" on quran_stations for select to authenticated using (true);
drop policy if exists "qst_admin_all" on quran_stations;
create policy "qst_admin_all" on quran_stations for all
  using (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')))
  with check (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')));

create table if not exists quran_fortresses (
  id uuid primary key default gen_random_uuid(),
  system_id uuid references quran_systems(id),
  code text not null,
  name text not null,
  color text not null,
  icon text,
  default_unit text default 'verse',
  order_index integer not null,
  is_enabled boolean default true
);
alter table quran_fortresses enable row level security;
drop policy if exists "staff read quran_fortresses" on quran_fortresses;
create policy "staff read quran_fortresses" on quran_fortresses for select to authenticated using (true);
drop policy if exists "qfo_admin_all" on quran_fortresses;
create policy "qfo_admin_all" on quran_fortresses for all
  using (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')))
  with check (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')));

create table if not exists quran_station_fortress_config (
  id uuid primary key default gen_random_uuid(),
  station_id uuid references quran_stations(id),
  fortress_id uuid references quran_fortresses(id),
  daily_amount numeric,
  unit text,
  is_enabled boolean default true,
  notes text,
  unique (station_id, fortress_id)
);
alter table quran_station_fortress_config enable row level security;
drop policy if exists "staff read quran_station_fortress_config" on quran_station_fortress_config;
create policy "staff read quran_station_fortress_config" on quran_station_fortress_config for select to authenticated using (true);
drop policy if exists "qcfg_admin_all" on quran_station_fortress_config;
create policy "qcfg_admin_all" on quran_station_fortress_config for all
  using (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')))
  with check (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')));

create table if not exists quran_student_plans (
  id uuid primary key default gen_random_uuid(),
  student_id bigint references students(id),
  login_id uuid references profiles(id),
  system_id uuid references quran_systems(id),
  current_station_id uuid references quran_stations(id),
  teacher_id uuid references profiles(id),
  start_date date not null,
  end_date_target date,
  end_date_actual date,
  status text default 'active',
  study_days integer[] default '{1,2,3,4,5}',
  rest_days integer[] default '{6,7}',
  far_review_mode text default 'daily_rotation',
  far_review_config jsonb,
  allow_early_progress boolean default true,
  notes text,
  created_by uuid references profiles(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  last_absence_check date
);
alter table quran_student_plans enable row level security;
drop policy if exists "plans scoped read" on quran_student_plans;
create policy "plans scoped read" on quran_student_plans for select to authenticated
  using (is_admin() or my_role() in ('executive','supervisor') or teacher_id = auth.uid() or login_id = auth.uid()
    or exists (select 1 from students s where s.id = quran_student_plans.student_id and (s.login_id = auth.uid() or s.parent_id = auth.uid())));
drop policy if exists "qplans_teacher" on quran_student_plans;
create policy "qplans_teacher" on quran_student_plans for all
  using (teacher_id = auth.uid() or exists (select 1 from profiles where id = auth.uid() and role = 'supervisor'))
  with check (teacher_id = auth.uid() or exists (select 1 from profiles where id = auth.uid() and role in ('supervisor','admin','executive')));
drop policy if exists "qplans_admin_all" on quran_student_plans;
create policy "qplans_admin_all" on quran_student_plans for all
  using (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')))
  with check (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')));

create table if not exists quran_student_assessment (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid references quran_student_plans(id),
  current_surah_no integer,
  current_ayah_no integer default 0,
  current_read_page integer default 1,
  current_listen_page integer default 1,
  prior_memorized jsonb default '[]',
  far_review_pool jsonb default '[]',
  notes text,
  created_at timestamptz default now()
);
alter table quran_student_assessment enable row level security;
drop policy if exists "assessment scoped read" on quran_student_assessment;
create policy "assessment scoped read" on quran_student_assessment for select to authenticated
  using (exists (select 1 from quran_student_plans qp where qp.id = quran_student_assessment.plan_id
    and (is_admin() or my_role() in ('executive','supervisor') or qp.teacher_id = auth.uid() or qp.login_id = auth.uid()
      or exists (select 1 from students s where s.id = qp.student_id and (s.login_id = auth.uid() or s.parent_id = auth.uid())))));
drop policy if exists "qassess_teacher" on quran_student_assessment;
create policy "qassess_teacher" on quran_student_assessment for all
  using (exists (select 1 from quran_student_plans p where p.id = quran_student_assessment.plan_id
    and (p.teacher_id = auth.uid() or exists (select 1 from profiles where id = auth.uid() and role in ('teacher','supervisor')))))
  with check (exists (select 1 from profiles where id = auth.uid() and role in ('teacher','supervisor','admin','executive')));
drop policy if exists "qassess_admin_all" on quran_student_assessment;
create policy "qassess_admin_all" on quran_student_assessment for all
  using (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')))
  with check (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')));

create table if not exists quran_plan_wards (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid references quran_student_plans(id),
  planned_date date not null,
  day_index integer not null,
  is_rest_day boolean default false,
  fortress_code text not null,
  fortress_id uuid references quran_fortresses(id),
  surah_no integer,
  surah_name text,
  ayah_from integer,
  ayah_to integer,
  page_from integer,
  page_to integer,
  whole_surah boolean default false,
  amount_label text,
  teacher_note text
);
alter table quran_plan_wards enable row level security;
drop policy if exists "wards scoped read" on quran_plan_wards;
create policy "wards scoped read" on quran_plan_wards for select to authenticated
  using (exists (select 1 from quran_student_plans qp where qp.id = quran_plan_wards.plan_id
    and (is_admin() or my_role() in ('executive','supervisor') or qp.teacher_id = auth.uid() or qp.login_id = auth.uid()
      or exists (select 1 from students s where s.id = qp.student_id and (s.login_id = auth.uid() or s.parent_id = auth.uid())))));
drop policy if exists "qwards_teacher" on quran_plan_wards;
create policy "qwards_teacher" on quran_plan_wards for all
  using (exists (select 1 from quran_student_plans p where p.id = quran_plan_wards.plan_id
    and (p.teacher_id = auth.uid() or exists (select 1 from profiles where id = auth.uid() and role = 'supervisor'))))
  with check (exists (select 1 from quran_student_plans p where p.id = quran_plan_wards.plan_id
    and (p.teacher_id = auth.uid() or exists (select 1 from profiles where id = auth.uid() and role in ('supervisor','admin','executive')))));
drop policy if exists "qwards_admin_all" on quran_plan_wards;
create policy "qwards_admin_all" on quran_plan_wards for all
  using (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')))
  with check (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')));

create table if not exists quran_ward_progress (
  id uuid primary key default gen_random_uuid(),
  ward_id uuid references quran_plan_wards(id),
  student_login_id uuid,
  status text default 'not_started',
  planned_for_date date,
  actual_date date,
  is_early boolean default false,
  is_late boolean default false,
  days_offset integer default 0,
  student_mastery numeric,
  student_note text,
  teacher_mastery numeric,
  teacher_note text,
  teacher_approved_at timestamptz,
  teacher_id uuid references profiles(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  plan_id uuid,
  unique (ward_id)
);
alter table quran_ward_progress enable row level security;
drop policy if exists "progress scoped read" on quran_ward_progress;
create policy "progress scoped read" on quran_ward_progress for select to authenticated
  using (student_login_id = auth.uid() or exists (select 1 from quran_plan_wards w join quran_student_plans qp on qp.id = w.plan_id
    where w.id = quran_ward_progress.ward_id and (is_admin() or my_role() in ('executive','supervisor') or qp.teacher_id = auth.uid() or qp.login_id = auth.uid()
      or exists (select 1 from students s where s.id = qp.student_id and (s.login_id = auth.uid() or s.parent_id = auth.uid())))));
drop policy if exists "qprog_owner_write" on quran_ward_progress;
create policy "qprog_owner_write" on quran_ward_progress for all to authenticated
  using (student_login_id = auth.uid() or exists (select 1 from quran_plan_wards w join quran_student_plans qp on qp.id = w.plan_id
    where w.id = quran_ward_progress.ward_id and (qp.login_id = auth.uid()
      or exists (select 1 from students s where s.id = qp.student_id and (s.login_id = auth.uid() or s.parent_id = auth.uid())))))
  with check (exists (select 1 from quran_plan_wards w join quran_student_plans qp on qp.id = w.plan_id
    where w.id = quran_ward_progress.ward_id and (qp.login_id = auth.uid()
      or exists (select 1 from students s where s.id = qp.student_id and (s.login_id = auth.uid() or s.parent_id = auth.uid())))));
drop policy if exists "qprog_teacher" on quran_ward_progress;
create policy "qprog_teacher" on quran_ward_progress for all
  using (exists (select 1 from quran_plan_wards w join quran_student_plans p on p.id = w.plan_id
    where w.id = quran_ward_progress.ward_id and (p.teacher_id = auth.uid() or exists (select 1 from profiles where id = auth.uid() and role = 'supervisor'))))
  with check (exists (select 1 from quran_plan_wards w join quran_student_plans p on p.id = w.plan_id
    where w.id = quran_ward_progress.ward_id and (p.teacher_id = auth.uid() or exists (select 1 from profiles where id = auth.uid() and role = 'supervisor'))));
drop policy if exists "qprog_admin_all" on quran_ward_progress;
create policy "qprog_admin_all" on quran_ward_progress for all
  using (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')))
  with check (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')));

-- daily-rate override per student plan; already has real RLS live (contrary to
-- the TODO comment left in 2026_plan_custom_rates_and_starting_station.sql)
create table if not exists quran_plan_fortress_rates (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid references quran_student_plans(id),
  fortress_id uuid references quran_fortresses(id),
  daily_amount numeric not null,
  unit text,
  created_at timestamptz default now(),
  unique (plan_id, fortress_id)
);
alter table quran_plan_fortress_rates enable row level security;
drop policy if exists "rates scoped read" on quran_plan_fortress_rates;
create policy "rates scoped read" on quran_plan_fortress_rates for select to authenticated
  using (exists (select 1 from quran_student_plans qp where qp.id = quran_plan_fortress_rates.plan_id
    and (is_admin() or my_role() in ('executive','supervisor') or qp.teacher_id = auth.uid() or qp.login_id = auth.uid()
      or exists (select 1 from students s where s.id = qp.student_id and (s.login_id = auth.uid() or s.parent_id = auth.uid())))));

create table if not exists quran_system_audit (
  id uuid primary key default gen_random_uuid(),
  system_id uuid references quran_systems(id),
  actor_id uuid references profiles(id),
  action text,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz default now()
);
alter table quran_system_audit enable row level security;
drop policy if exists "qaud_admin_all" on quran_system_audit;
create policy "qaud_admin_all" on quran_system_audit for all
  using (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')))
  with check (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')));

create table if not exists quran_notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  kind text not null,
  payload jsonb,
  read_at timestamptz,
  created_at timestamptz default now()
);
alter table quran_notifications enable row level security;
drop policy if exists "quran_notifications owner read" on quran_notifications;
create policy "quran_notifications owner read" on quran_notifications for select to authenticated using (user_id = auth.uid());
drop policy if exists "quran_notifications owner write" on quran_notifications;
create policy "quran_notifications owner write" on quran_notifications for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "quran_notifications owner delete" on quran_notifications;
create policy "quran_notifications owner delete" on quran_notifications for delete to authenticated using (user_id = auth.uid());
drop policy if exists "quran_notifications insert any" on quran_notifications;
create policy "quran_notifications insert any" on quran_notifications for insert to authenticated with check (true);
-- NOTE (flagged, not fixed here): the live "insert any" policy lets ANY
-- authenticated user insert a quran_notifications row for ANY user_id — the
-- same in-platform impersonation pattern that SETUP.sql already had to fix
-- once for the `notifications` table (see SETUP.sql:1734-1762). Tracked as a
-- P1 item, not touched in this migration to keep this file purely additive/
-- documentary — see the audit report, item P1-#19 equivalent.
drop policy if exists "qnotifs_admin_all" on quran_notifications;
create policy "qnotifs_admin_all" on quran_notifications for all
  using (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')))
  with check (exists (select 1 from profiles where id = auth.uid() and role in ('admin','executive')));

-- ---------------------------------------------------------------------------
-- Indexes that make the above usable at scale (guarded, additive only)
-- ---------------------------------------------------------------------------
create index if not exists idx_quran_plan_wards_plan_date on quran_plan_wards(plan_id, planned_date);
create index if not exists idx_quran_ward_progress_ward on quran_ward_progress(ward_id);
create index if not exists idx_quran_student_plans_login on quran_student_plans(login_id);
create index if not exists idx_quran_student_plans_teacher on quran_student_plans(teacher_id);
create index if not exists idx_husoon_marks_student_day on husoon_marks(student_id, day);
create index if not exists idx_attendance_student_day on attendance(student_id, day);
