-- ============================================================================
-- 002_security_and_progress_tracking.sql
--
-- Additive, non-destructive migration. Every statement is guarded
-- (`if not exists` / `create or replace` / `drop policy if exists`), so it is
-- safe to run once against the live project (yvloiecymqbhpoizfucl). Nothing
-- here deletes or mutates existing rows. Written against the live schema,
-- verified via the Supabase Management API before writing any statement.
--
-- Covers:
--  1. Soft-delete for students (deleted_at column) instead of hard DELETE.
--  2. admin_actions_log — audit trail for sensitive staff actions.
--  3. quran_ward_progress.marked_by_role — who actually marked a ward done
--     (student / parent / teacher), computed deterministically server-side.
--  4. Atomic RPCs for payment confirmation/rejection and subsidy rejection,
--     replacing multi-step client-side writes that had no error handling
--     between steps (a partial failure could leave payment/enrollment state
--     inconsistent with zero admin-facing error).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1) Soft-delete for students
-- ---------------------------------------------------------------------------
alter table students add column if not exists deleted_at timestamptz;
alter table students add column if not exists deleted_by uuid references profiles(id);
alter table students add column if not exists delete_reason text;

-- ---------------------------------------------------------------------------
-- 2) Audit log for sensitive admin/staff actions
-- ---------------------------------------------------------------------------
create table if not exists admin_actions_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references profiles(id),
  actor_role text,
  action text not null,
  target_table text,
  target_id text,
  details jsonb,
  created_at timestamptz default now()
);
alter table admin_actions_log enable row level security;
drop policy if exists "admin_actions_log staff read" on admin_actions_log;
create policy "admin_actions_log staff read" on admin_actions_log for select to authenticated
  using (is_admin() or my_role() in ('executive','supervisor'));
-- عمدًا لا توجد سياسة INSERT/UPDATE/DELETE للعميل: الكتابة فقط عبر الدوال
-- SECURITY DEFINER أدناه، فلا يقدر أي مستخدم يزوّر أو يمسح سجل التدقيق.

create or replace function log_admin_action(p_action text, p_target_table text, p_target_id text, p_details jsonb default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into admin_actions_log(actor_id, actor_role, action, target_table, target_id, details)
  values (auth.uid(), (select role::text from profiles where id = auth.uid()), p_action, p_target_table, p_target_id, p_details);
end;
$$;

-- ---------------------------------------------------------------------------
-- 3) soft_delete_student — يستبدل الحذف النهائي بعلامة تاريخية + سجل تدقيق
-- ---------------------------------------------------------------------------
create or replace function soft_delete_student(p_student_id bigint, p_reason text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_name text;
begin
  if not (is_admin() or my_role() in ('executive','supervisor')) then
    return jsonb_build_object('ok', false, 'error', 'forbidden');
  end if;
  select full_name into v_name from students where id = p_student_id;
  if v_name is null then
    return jsonb_build_object('ok', false, 'error', 'not_found');
  end if;
  update students set deleted_at = now(), deleted_by = auth.uid(), delete_reason = p_reason
  where id = p_student_id;
  perform log_admin_action('soft_delete_student', 'students', p_student_id::text, jsonb_build_object('full_name', v_name, 'reason', p_reason));
  return jsonb_build_object('ok', true);
end;
$$;

-- ---------------------------------------------------------------------------
-- 4) confirm_payment / reject_payment / reject_subsidy
--    نفس منطق العميل الحالي (confirmPay/rejectPay/rejectSubsidy في index.html)
--    حرفيًا، لكن كعملية واحدة ذرّية على السيرفر بدل خطوتين منفصلتين بلا تحقق
--    خطأ بينهما. الإشعارات لسه بتتبعت من العميل بعد نجاح الاستدعاء (نفس
--    pushNotif المُختبَر) — الدالة بترجع بيانات التواصل اللازمة لذلك فقط.
-- ---------------------------------------------------------------------------
create or replace function confirm_payment(p_payment_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_student_id bigint;
  v_jr_id bigint;
  v_is_renewal boolean;
  v_sub_end timestamptz;
  v_base timestamptz;
  v_next_end timestamptz;
  v_full_name text;
  v_login_id uuid;
  v_parent_id uuid;
  v_updated int;
begin
  if not (is_admin() or my_role() in ('executive','supervisor')) then
    return jsonb_build_object('ok', false, 'error', 'forbidden');
  end if;

  select student_id, join_request_id into v_student_id, v_jr_id from payments where id = p_payment_id and status = 'pending';
  if v_student_id is null then
    return jsonb_build_object('ok', false, 'error', 'not_found_or_already_processed');
  end if;

  v_is_renewal := (v_jr_id is null);
  select sub_end, full_name, login_id, parent_id into v_sub_end, v_full_name, v_login_id, v_parent_id
  from students where id = v_student_id;

  v_base := now();
  if v_is_renewal and v_sub_end is not null and v_sub_end > v_base then
    v_base := v_sub_end;
  end if;
  v_next_end := v_base + interval '1 month';

  update payments set status = 'paid', paid_at = now(), confirmed_by = auth.uid()
  where id = p_payment_id and status = 'pending';
  get diagnostics v_updated = row_count;
  if v_updated = 0 then
    return jsonb_build_object('ok', false, 'error', 'race_condition_already_processed');
  end if;

  update students set
    enrollment_status = 'active',
    sub_start = case when v_is_renewal then coalesce(v_sub_end, now()) else now() end,
    sub_end = v_next_end,
    sub_anchored = v_is_renewal
  where id = v_student_id;

  perform log_admin_action('confirm_payment', 'payments', p_payment_id::text,
    jsonb_build_object('student_id', v_student_id, 'is_renewal', v_is_renewal, 'new_sub_end', v_next_end));

  return jsonb_build_object('ok', true, 'is_renewal', v_is_renewal, 'student_id', v_student_id,
    'full_name', v_full_name, 'login_id', v_login_id, 'parent_id', v_parent_id);
end;
$$;

create or replace function reject_payment(p_payment_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_student_id bigint;
  v_full_name text;
  v_login_id uuid;
  v_parent_id uuid;
  v_updated int;
begin
  if not (is_admin() or my_role() in ('executive','supervisor')) then
    return jsonb_build_object('ok', false, 'error', 'forbidden');
  end if;

  update payments set status = 'rejected' where id = p_payment_id and status = 'pending';
  get diagnostics v_updated = row_count;
  if v_updated = 0 then
    return jsonb_build_object('ok', false, 'error', 'not_found_or_already_processed');
  end if;

  select student_id into v_student_id from payments where id = p_payment_id;
  select full_name, login_id, parent_id into v_full_name, v_login_id, v_parent_id from students where id = v_student_id;

  perform log_admin_action('reject_payment', 'payments', p_payment_id::text, jsonb_build_object('student_id', v_student_id));

  return jsonb_build_object('ok', true, 'student_id', v_student_id, 'full_name', v_full_name, 'login_id', v_login_id, 'parent_id', v_parent_id);
end;
$$;

create or replace function reject_subsidy(p_request_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_student_id bigint;
  v_full_name text;
  v_login_id uuid;
  v_parent_id uuid;
  v_updated int;
begin
  if not (is_admin() or my_role() in ('executive','supervisor')) then
    return jsonb_build_object('ok', false, 'error', 'forbidden');
  end if;

  update join_requests set status = 'rejected', reviewed_by = auth.uid() where id = p_request_id and status = 'pending';
  get diagnostics v_updated = row_count;
  if v_updated = 0 then
    return jsonb_build_object('ok', false, 'error', 'not_found_or_already_processed');
  end if;

  select student_id into v_student_id from join_requests where id = p_request_id;
  select full_name, login_id, parent_id into v_full_name, v_login_id, v_parent_id from students where id = v_student_id;

  perform log_admin_action('reject_subsidy', 'join_requests', p_request_id::text, jsonb_build_object('student_id', v_student_id));

  return jsonb_build_object('ok', true, 'student_id', v_student_id, 'full_name', v_full_name, 'login_id', v_login_id, 'parent_id', v_parent_id);
end;
$$;

-- ---------------------------------------------------------------------------
-- 5) من علّم الورد فعليًا؟ (طالب / ولي أمر / معلم) — إضافة محسوبة بدقة على
--    السيرفر من هوية المتصل الفعلية، وليست قيمة يرسلها العميل (غير موثوقة).
-- ---------------------------------------------------------------------------
alter table quran_ward_progress add column if not exists marked_by_role text;
alter table quran_ward_progress add column if not exists marked_by_id uuid;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'quran_ward_progress_marked_by_role_check') then
    alter table quran_ward_progress add constraint quran_ward_progress_marked_by_role_check
      check (marked_by_role is null or marked_by_role in ('student','parent','teacher'));
  end if;
end $$;

create or replace function quran_mark_ward(
  p_ward_id uuid, p_status text default null::text, p_planned_for_date date default null::date,
  p_actual_date date default null::date, p_is_early boolean default null::boolean, p_is_late boolean default null::boolean,
  p_days_offset integer default null::integer, p_student_mastery integer default null::integer,
  p_student_note text default null::text, p_teacher_note text default null::text,
  p_clear_teacher_note boolean default false, p_touch_teacher boolean default false, p_teacher_approve boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_is_owner boolean;
  v_is_staff boolean;
  v_is_student_self boolean;
  v_marked_role text;
begin
  select exists(
    select 1 from quran_plan_wards w
    join quran_student_plans qp on qp.id = w.plan_id
    where w.id = p_ward_id
      and (qp.login_id = auth.uid()
           or exists (select 1 from students s where s.id = qp.student_id
                      and (s.login_id = auth.uid() or s.parent_id = auth.uid())))
  ) into v_is_owner;

  select exists(
    select 1 from quran_plan_wards w
    join quran_student_plans qp on qp.id = w.plan_id
    where w.id = p_ward_id
      and (qp.teacher_id = auth.uid() or is_admin()
           or my_role() = any(array['executive','supervisor']::user_role[]))
  ) into v_is_staff;

  if not (v_is_owner or v_is_staff) then
    return jsonb_build_object('error','forbidden');
  end if;

  -- تحديد من علّم الورد فعليًا: حساب المتصل نفسه (login_id) = الطالب، أو
  -- حساب ولي الأمر المرتبط = ولي أمر، أو معلم/إدارة معتمِد = معلم. القيمة
  -- محسوبة هنا من هوية المتصل الحقيقية (auth.uid())، لا يرسلها العميل أبدًا.
  if p_touch_teacher or p_teacher_approve or (v_is_staff and not v_is_owner) then
    v_marked_role := 'teacher';
  elsif v_is_owner then
    select exists(
      select 1 from quran_plan_wards w join quran_student_plans qp on qp.id = w.plan_id
      where w.id = p_ward_id and qp.login_id = auth.uid()
    ) into v_is_student_self;
    v_marked_role := case when v_is_student_self then 'student' else 'parent' end;
  end if;

  insert into quran_ward_progress(
    ward_id, student_login_id, status, planned_for_date, actual_date,
    is_early, is_late, days_offset, student_mastery, student_note,
    teacher_note, teacher_id, teacher_approved_at, updated_at, marked_by_role, marked_by_id
  ) values (
    p_ward_id,
    case when v_is_owner then auth.uid() else null end,
    coalesce(p_status,'not_started'), p_planned_for_date, p_actual_date,
    coalesce(p_is_early,false), coalesce(p_is_late,false), p_days_offset,
    p_student_mastery, p_student_note,
    p_teacher_note,
    case when p_touch_teacher or p_teacher_approve then auth.uid() else null end,
    case when p_teacher_approve then now() else null end,
    now(), v_marked_role, auth.uid()
  )
  on conflict (ward_id) do update set
    status = coalesce(p_status, quran_ward_progress.status),
    planned_for_date = coalesce(p_planned_for_date, quran_ward_progress.planned_for_date),
    actual_date = coalesce(p_actual_date, quran_ward_progress.actual_date),
    is_early = coalesce(p_is_early, quran_ward_progress.is_early),
    is_late = coalesce(p_is_late, quran_ward_progress.is_late),
    days_offset = coalesce(p_days_offset, quran_ward_progress.days_offset),
    student_mastery = coalesce(p_student_mastery, quran_ward_progress.student_mastery),
    student_note = coalesce(p_student_note, quran_ward_progress.student_note),
    teacher_note = case when p_clear_teacher_note then null else coalesce(p_teacher_note, quran_ward_progress.teacher_note) end,
    teacher_id = case when p_touch_teacher or p_teacher_approve then auth.uid() else quran_ward_progress.teacher_id end,
    teacher_approved_at = case when p_teacher_approve then now() else quran_ward_progress.teacher_approved_at end,
    updated_at = now(),
    marked_by_role = coalesce(v_marked_role, quran_ward_progress.marked_by_role),
    marked_by_id = coalesce(auth.uid(), quran_ward_progress.marked_by_id);

  return jsonb_build_object('ok', true);
end;
$$;

-- ---------------------------------------------------------------------------
-- 6) quran_notifications: نفس ثغرة انتحال الصفة اللي أُصلحت من قبل لجدول
--    notifications العادي (SETUP.sql) لكنها كانت لسه موجودة هنا — أي مستخدم
--    مسجّل دخول يقدر يُدرج إشعار quran_notifications لأي user_id بأي محتوى.
--    نفس نمط الربط بعلاقة فعلية (محادثة مشتركة، أو معلم↔طالبه/وليّ أمره).
-- ---------------------------------------------------------------------------
drop policy if exists "quran_notifications insert any" on quran_notifications;
drop policy if exists "quran_notifications insert scoped" on quran_notifications;
create policy "quran_notifications insert scoped" on quran_notifications for insert to authenticated with check (
  is_admin() or my_role() = any(array['supervisor','executive']::user_role[])
  or user_id = auth.uid()
  or exists (
    select 1 from chats c where auth.uid() = any(c.party_ids) and quran_notifications.user_id = any(c.party_ids)
  )
  or exists (
    select 1 from students s
    where (s.login_id = quran_notifications.user_id or s.parent_id = quran_notifications.user_id)
      and (
        s.chosen_teacher_id = auth.uid()
        or exists (select 1 from groups g where g.id = s.group_id and g.teacher_id = auth.uid())
      )
  )
  or exists (
    select 1 from students s
    where (s.login_id = auth.uid() or s.parent_id = auth.uid())
      and (
        s.chosen_teacher_id = quran_notifications.user_id
        or exists (select 1 from groups g where g.id = s.group_id and g.teacher_id = quran_notifications.user_id)
      )
  )
);

-- ---------------------------------------------------------------------------
-- 7) إلزام تغيير كلمة المرور عند أول دخول لأي حساب أُنشئ/أُعيد تعيينه من طرف
--    آخر (طالب ينشئ حساب ولي أمره، إدارة تعيد تعيين كلمة مرور، إنشاء حساب
--    طاقم). العلم يُضبط داخل نفس الدوال SECURITY DEFINER التي تنشئ/تُعيد
--    تعيين كلمة المرور — بلا أي تغيير آخر في منطقها الأصلي.
-- ---------------------------------------------------------------------------
alter table profiles add column if not exists must_change_password boolean default false;

create or replace function admin_reset_password(target_email text, new_password text)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'extensions'
as $$
declare
  target_user_id uuid;
  caller_role text;
begin
  select role into caller_role from profiles where id = auth.uid();
  if caller_role is null or caller_role not in ('admin','executive','supervisor') then
    return jsonb_build_object('ok', false, 'error', 'غير مصرح لك بهذا الإجراء');
  end if;

  select id into target_user_id from auth.users where email = target_email;
  if target_user_id is null then
    return jsonb_build_object('ok', false, 'error', 'لا يوجد مستخدم بهذا البريد');
  end if;

  update auth.users
  set encrypted_password = crypt(new_password, gen_salt('bf')),
      updated_at = now()
  where id = target_user_id;

  update profiles set must_change_password = true where id = target_user_id;

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function create_linked_account(p_email text, p_password text, p_name text, p_role text, p_student_id bigint, p_gender text default null::text)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'extensions'
as $$
declare
  new_user_id uuid;
  existing_id uuid;
  caller_role text;
  existing_link uuid;
begin
  if p_role not in ('student','parent') then
    return jsonb_build_object('ok', false, 'error', 'هذه الدالة تنشئ حسابات الطلاب وأولياء الأمور فقط');
  end if;

  select role into caller_role from profiles where id = auth.uid();
  if p_student_id is not null then
    if p_role = 'student' then
      select login_id into existing_link from students where id = p_student_id;
    else
      select parent_id into existing_link from students where id = p_student_id;
    end if;
    if existing_link is not null
       and (caller_role is null or caller_role not in ('admin','executive','supervisor')) then
      return jsonb_build_object('ok', false, 'error', 'هذا الطالب مرتبط بحساب بالفعل');
    end if;
  end if;

  perform pg_advisory_xact_lock(hashtext(lower(p_email)));

  select id into existing_id from auth.users where email = p_email;
  if existing_id is not null then
    return jsonb_build_object('ok', false, 'error', 'هذا البريد مستخدم بالفعل');
  end if;

  new_user_id := gen_random_uuid();

  insert into auth.users (
    id, instance_id, aud, role, email, encrypted_password,
    email_confirmed_at, created_at, updated_at,
    raw_app_meta_data, raw_user_meta_data, is_super_admin,
    confirmation_token, recovery_token, email_change,
    email_change_token_new, email_change_token_current,
    phone_change, phone_change_token, reauthentication_token
  ) values (
    new_user_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
    p_email, crypt(p_password, gen_salt('bf')),
    now(), now(), now(),
    '{"provider":"email","providers":["email"]}', jsonb_build_object('full_name', p_name, 'role', p_role),
    false,
    '', '', '', '', '', '', '', ''
  );

  insert into auth.identities (
    id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at
  ) values (
    gen_random_uuid(), new_user_id, new_user_id::text,
    jsonb_build_object('sub', new_user_id::text, 'email', p_email),
    'email', now(), now(), now()
  );

  insert into profiles (id, role, full_name, email, gender, must_change_password)
  values (new_user_id, p_role::user_role, p_name, p_email, p_gender, true)
  on conflict (id) do update set role=excluded.role, full_name=excluded.full_name, email=excluded.email,
    gender=coalesce(excluded.gender, profiles.gender), must_change_password=true;

  if p_role = 'student' and p_student_id is not null then
    update students set login_id = new_user_id, gender = coalesce(p_gender, gender) where id = p_student_id;
  elsif p_role = 'parent' and p_student_id is not null then
    update students set parent_id = new_user_id where id = p_student_id;
  end if;

  return jsonb_build_object('ok', true, 'user_id', new_user_id);
exception
  when unique_violation then
    return jsonb_build_object('ok', false, 'error', 'هذا البريد مستخدم بالفعل');
end;
$$;

create or replace function create_staff_account(p_email text, p_password text, p_name text, p_role text, p_gender text default null::text, p_title text default null::text, p_department text default null::text, p_specialty text default null::text)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'extensions'
as $$
declare
  new_user_id uuid;
  existing_id uuid;
begin
  if not is_admin() then
    return jsonb_build_object('ok', false, 'error', 'هذا الإجراء مقصور على المدير فقط');
  end if;
  if p_role not in ('admin','executive','supervisor','teacher') then
    return jsonb_build_object('ok', false, 'error', 'دور غير صالح');
  end if;

  perform pg_advisory_xact_lock(hashtext(lower(p_email)));

  select id into existing_id from auth.users where email = p_email;
  if existing_id is not null then
    return jsonb_build_object('ok', false, 'error', 'هذا البريد مستخدم بالفعل');
  end if;

  new_user_id := gen_random_uuid();

  insert into auth.users (
    id, instance_id, aud, role, email, encrypted_password,
    email_confirmed_at, created_at, updated_at,
    raw_app_meta_data, raw_user_meta_data, is_super_admin,
    confirmation_token, recovery_token, email_change,
    email_change_token_new, email_change_token_current,
    phone_change, phone_change_token, reauthentication_token
  ) values (
    new_user_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
    p_email, crypt(p_password, gen_salt('bf')),
    now(), now(), now(),
    '{"provider":"email","providers":["email"]}', jsonb_build_object('full_name', p_name, 'role', p_role),
    false,
    '', '', '', '', '', '', '', ''
  );

  insert into auth.identities (
    id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at
  ) values (
    gen_random_uuid(), new_user_id, new_user_id::text,
    jsonb_build_object('sub', new_user_id::text, 'email', p_email),
    'email', now(), now(), now()
  );

  insert into profiles (id, role, full_name, email, gender, reports_to, title, department, specialty, is_available, must_change_password)
  values (new_user_id, p_role::user_role, p_name, p_email, p_gender, auth.uid(), p_title, p_department, p_specialty,
          case when p_role='teacher' then true else null end, true)
  on conflict (id) do update set
    role=excluded.role, full_name=excluded.full_name, email=excluded.email,
    gender=coalesce(excluded.gender, profiles.gender), reports_to=excluded.reports_to,
    title=excluded.title, department=excluded.department, specialty=excluded.specialty,
    is_available=coalesce(excluded.is_available, profiles.is_available), must_change_password=true;

  return jsonb_build_object('ok', true, 'user_id', new_user_id);
exception
  when unique_violation then
    return jsonb_build_object('ok', false, 'error', 'هذا البريد مستخدم بالفعل');
end;
$$;

-- ملاحظة مهمة (مقصودة، غير منفَّذة هنا): ربط إتمام الورد تلقائيًا برفع
-- points/pages/streak على جدول students يحتاج معادلة عمل واضحة (كم نقطة
-- لكل نوع حصن؟ هل "المراجعة البعيدة" تُحتسب زي "الحفظ الجديد"؟ قاعدة
-- التتابع اليومي streak إزاي تُحسب بدقة؟) — دي غير موجودة في أي مكان بالكود
-- الحالي (points تُمنح فقط من "تحدي رجل الأسبوع" المنفصل تمامًا)، ومحتاجة
-- قرار عمل صريح من الإدارة قبل ما تتحوّل لكود، مش افتراض من عندي. مُعلَّم
-- كبند منفصل يحتاج اعتمادك.
