-- ============================================================================
-- 005_plan_edit_history_and_remedial_wards.sql
--
-- سياق مهم اكتُشف أثناء بناء هذا الملف: خطة الطالب أصلاً مرنة بشكل كبير بالفعل
-- (qUpdatePlanStatus, qSaveWardEdit/qEditWard مع ترحيل الزيادة/النقصان,
-- qRescheduleRemaining, qCatchUpPlan, qCheckTransition/qDoTransition) —
-- التقرير الأصلي لم يكن دقيقًا في وصفها كـ"جامدة". الفجوة الحقيقية المتبقية:
--   ١) qUpdatePlanStatus كانت الوحيدة اللي "تحاول" تسجّل في سجل تدقيق
--      (quran_system_audit) — لكن بصمت تفشل لأي معلم عادي، لأن سياسة RLS
--      الوحيدة على الجدول ده مقصورة على admin/executive فقط (qaud_admin_all).
--      باقي أدوات التعديل (تعديل ورد، إعادة جدولة، استدراك، انتقال محطة) ما
--      كانتش بتسجّل أي حاجة إطلاقًا.
--   ٢) لا توجد أداة لإضافة "مراجعة علاجية" — ورد إضافي خارج جدول الخطة الأصلي.
--   ٣) لا توجد أداة لإعادة ترتيب المحطات لطالب بعينه (أُجِّلت عمدًا — تحتاج
--      قرار تصميم: حدود المحطات مبنية على مدى آيات فعلي، وإعادة ترتيبها لطالب
--      واحد بمعزل عن القالب تحتاج تصميمًا أعمق، غير منفَّذة هنا).
--
-- هذا الملف: جدول تدقيق مخصّص لخطط القرآن (بدل تحميل quran_system_audit فوق
-- طاقته)، بصلاحيات RLS صحيحة تشمل المعلم صاحب الخطة فعليًا لا الإدارة فقط.
-- ============================================================================

create table if not exists quran_plan_edits (
  id bigint generated by default as identity primary key,
  plan_id uuid references quran_student_plans(id),
  actor_id uuid references profiles(id),
  actor_role text,
  action text not null,
  reason text,
  before_data jsonb,
  after_data jsonb,
  expected_impact text,
  created_at timestamptz default now()
);
alter table quran_plan_edits enable row level security;
drop policy if exists "plan edits read" on quran_plan_edits;
create policy "plan edits read" on quran_plan_edits for select to authenticated
  using (exists (select 1 from quran_student_plans qp where qp.id = quran_plan_edits.plan_id
    and (is_admin() or my_role() in ('executive','supervisor') or qp.teacher_id = auth.uid() or qp.login_id = auth.uid()
      or exists (select 1 from students s where s.id = qp.student_id and (s.login_id = auth.uid() or s.parent_id = auth.uid())))));
drop policy if exists "plan edits write" on quran_plan_edits;
create policy "plan edits write" on quran_plan_edits for insert to authenticated
  with check (actor_id = auth.uid() and exists (select 1 from quran_student_plans qp where qp.id = quran_plan_edits.plan_id
    and (is_admin() or my_role() in ('executive','supervisor') or qp.teacher_id = auth.uid())));
create index if not exists idx_quran_plan_edits_plan on quran_plan_edits(plan_id, created_at desc);

-- إضافة مراجعة علاجية / تصحيح تلاوة: ورد إضافي خارج الجدول الأصلي، بتاريخ
-- يحدده المعلم، بلا التأثير على أي ورد آخر مجدوَل بالفعل. staff/teacher only.
create or replace function quran_add_remedial_ward(
  p_plan_id uuid, p_planned_date date, p_fortress_code text, p_amount_label text, p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_new_ward_id uuid;
  v_is_staff boolean;
begin
  select exists(
    select 1 from quran_student_plans qp where qp.id = p_plan_id
    and (qp.teacher_id = auth.uid() or is_admin() or my_role() = any(array['executive','supervisor']::user_role[]))
  ) into v_is_staff;
  if not v_is_staff then
    return jsonb_build_object('ok', false, 'error', 'forbidden');
  end if;

  insert into quran_plan_wards (plan_id, planned_date, day_index, is_rest_day, fortress_code, amount_label, teacher_note)
  values (p_plan_id, p_planned_date, -1, false, p_fortress_code, coalesce(p_amount_label, 'مراجعة علاجية'), p_reason)
  returning id into v_new_ward_id;

  insert into quran_plan_edits (plan_id, actor_id, actor_role, action, reason, after_data, expected_impact)
  values (p_plan_id, auth.uid(), (select role::text from profiles where id = auth.uid()), 'add_remedial_ward', p_reason,
    jsonb_build_object('ward_id', v_new_ward_id, 'planned_date', p_planned_date, 'fortress_code', p_fortress_code),
    'إضافة يوم مراجعة علاجية إضافي — لا يغيّر مواعيد بقية الخطة');

  return jsonb_build_object('ok', true, 'ward_id', v_new_ward_id);
end;
$$;
