-- ============================================================================
-- 013_legacy_ward_migration_assessment.sql
--
-- تقييم فعلي (لا يغيّر أي بيانات) لمدى وجود "أوراد نصية قديمة" تحتاج ترحيل
-- لنطاقات منظمة، كما طُلب صراحةً في المرحلة التاسعة من إعادة الهيكلة.
--
-- الخلاصة بعد فحص كل البيانات الحية (٣٬٤٣٦ ورد عبر ٥ أنواع حصون):
--
--   new_hifz (762 ورد)     — ١٠٠٪ مُهيكَل بالكامل (سورة + مدى آيات فعلي)
--   review_far (804 ورد)   — ١٠٠٪ يستخدم whole_surah=true (مراجعة سورة كاملة)،
--                            تصميم صحيح ومقصود، وليس بيانات ناقصة
--   reading (533 ورد)      — ١٠٠٪ مبني على page_from/page_to (وحدته صفحات
--                            بطبيعته، لا آيات) — تصميم صحيح
--   listening (533 ورد)    — نفس reading تمامًا، ١٠٠٪ سليم
--   review_near (804 ورد)  — ٩٥٪ مُهيكَل بالكامل. الـ٥٪ الباقية (43 صفاً، كلها
--                            بخطة طالب واحد) ليست بيانات قديمة تحتاج تحويلاً،
--                            بل صفوف "لا مراجعة قريبة بعد" — أيام مستقبلية
--                            حقيقية لطالب لسه ما حفظش كفاية ليكون له مراجعة
--                            قريبة أصلاً، وأمر متوقَّع من محرك التوليد نفسه.
--
-- النتيجة: لا يوجد رصيد ترحيل حقيقي (no legacy debt) يحتاج تنفيذاً — محرك
-- توليد الخطط كان بالفعل يُنتج بيانات مُهيكَلة بالكامل قبل هذه المرحلة، فقط
-- بلا مرجع قرآني يتحقق منها (وهو ما أضافته migrations 008-009).
--
-- الشيء الوحيد المكتشَف فعليًا يستحق الإصلاح (كود، لا بيانات): محرك التوليد
-- يُمثّل حالة "لا مراجعة قريبة بعد" بطريقتين مختلفتين لنفس المعنى — أحيانًا
-- surah_no فارغ تمامًا، وأحيانًا surah_no موجود (كموضع مرجعي) لكن بلا مدى
-- آيات ولا whole_surah=true. توحيد التمثيل مؤجَّل لمهمة تنظيف كود منفصلة
-- (لا يؤثر على صحة البيانات الحالية، فقط اتساق داخلي).
--
-- الاستعلامات التالية (قراءة فقط) هي ما استُخدم فعليًا للتحقق أعلاه، محفوظة
-- هنا كوثيقة قابلة لإعادة التشغيل لأي تدقيق مستقبلي.
-- ============================================================================

-- توزيع الهيكلة حسب نوع الحصن
-- select fortress_code, count(*) as total,
--   count(*) filter (where surah_no is null) as no_surah,
--   count(*) filter (where surah_no is not null and (ayah_from is null or ayah_to is null)) as partial_range
-- from quran_plan_wards group by fortress_code order by total desc;

-- تأكيد أن كل حالات "الهيكلة الجزئية" مبررة (page-based أو whole_surah أو placeholder حقيقي)
-- select fortress_code,
--   count(*) filter (where page_from is not null and page_to is not null) as has_pages,
--   count(*) filter (where whole_surah=true) as whole_surah_true
-- from quran_plan_wards where fortress_code in ('reading','listening','review_near','review_far')
-- group by fortress_code;

select 'no functional migration required — see comments above' as assessment;
