-- ============================================================================
-- 015_help_requests.sql
--
-- زرار "مساعدة" في ورد اليوم كان أُزيل قبل هذه الجلسة بقرار صريح، لأن نسخته
-- القديمة كانت بلا فائدة فعلية: الطالب يقول "محتاج مساعدة" بلا أي تصنيف
-- لنوعها، والمعلم يستلم إشعاراً عاماً بلا سياق يقدر يتصرّف بيه. النسخة هنا
-- مختلفة جوهريًا: فئة واضحة + الورد المحدَّد بالذات + إمكانية إغلاق الطلب.
-- ============================================================================

create table if not exists quran_help_requests (
  id bigint generated by default as identity primary key,
  ward_id uuid references quran_plan_wards(id),
  plan_id uuid references quran_student_plans(id),
  requested_by uuid references profiles(id),
  category text not null check (category in ('memorization_difficulty','recitation_tajweed','review_confusion','schedule_issue','other')),
  note text,
  status text not null default 'open' check (status in ('open','resolved')),
  resolved_by uuid references profiles(id),
  resolved_at timestamptz,
  resolution_note text,
  created_at timestamptz default now()
);
alter table quran_help_requests enable row level security;

drop policy if exists "help requests owner insert" on quran_help_requests;
create policy "help requests owner insert" on quran_help_requests for insert to authenticated
  with check (requested_by = auth.uid() and exists (
    select 1 from quran_student_plans qp where qp.id = plan_id
      and (qp.login_id = auth.uid() or exists (select 1 from students s where s.id = qp.student_id and (s.login_id = auth.uid() or s.parent_id = auth.uid())))
  ));

drop policy if exists "help requests read" on quran_help_requests;
create policy "help requests read" on quran_help_requests for select to authenticated
  using (exists (
    select 1 from quran_student_plans qp where qp.id = quran_help_requests.plan_id
      and (is_admin() or my_role() in ('executive','supervisor') or qp.teacher_id = auth.uid() or qp.login_id = auth.uid()
        or exists (select 1 from students s where s.id = qp.student_id and (s.login_id = auth.uid() or s.parent_id = auth.uid())))
  ));

-- الحل يقتصر على المعلم/الإدارة — لا الطالب نفسه (يمنع إغلاق طلبه بنفسه بلا رد فعلي)
drop policy if exists "help requests teacher resolve" on quran_help_requests;
create policy "help requests teacher resolve" on quran_help_requests for update to authenticated
  using (exists (
    select 1 from quran_student_plans qp where qp.id = quran_help_requests.plan_id
      and (is_admin() or my_role() in ('executive','supervisor') or qp.teacher_id = auth.uid())
  ))
  with check (exists (
    select 1 from quran_student_plans qp where qp.id = quran_help_requests.plan_id
      and (is_admin() or my_role() in ('executive','supervisor') or qp.teacher_id = auth.uid())
  ));

create index if not exists idx_quran_help_requests_plan_open on quran_help_requests(plan_id) where status = 'open';
